apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}p
    protocol: TCP
    port: 80
    targetPort: http-web-svc